### ISSUE TITLE
Passing input files

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/compound-embedding#1]
In the lite package, I don't know how to pass:
- List of smiles
- CSV file with list of smiles
And how to get an output file with all the embeddings instead of just a print in the CLI

I have added the ideal funtionality in the readme file, both for the CLI and for running a single .py file, which I have named embed.py - this will allow users to simply run this rather can copying the chunk of code and modifying it. 
Now, when I try to pass several smiles in the CLI, i get the following error: 
[10:53:44] SMILES Parse Error: syntax error while parsing: [CCCCON,
[10:53:44] SMILES Parse Error: Failed parsing SMILES '[CCCCON,' for input: '[CCCCON,'
Segmentation fault (core dumped)

How can I pass more than one SMILES and collect its output in a .csv format ?

**Comment by leoank** [comment]
You can pass multiple smiles and save them as follows:
```bash
eosce embed --out embeddings.npz SMILE1 SMILE2 SMILE3 ...
```
Currently, CSV output is not supported.

**Comment by GemmaTuron** [comment]
I see, thanks Ank did not know about this option. A few comments:
- Is there a reason not to get CSV files as output? They are a bit larger, but almost everything we do downstream will be prepared for csv inputs, so that would be good to have
- More important is to be able to pass a list of smiles from a csv file, this is certainly what we always have at the beginning of the pipeline

**Comment by leoank** [comment]
There is no reason to not support CSV files. It was just easier to implement the CLI without CSV support in the initial version. I'll add support for CSV in my next commit.

**Comment by leoank** [comment]
Hey @GemmaTuron, use the cli help to know how to use the csv input and output feature

```bash
eosce embed --help
```

But for a quickstart, this should work

```bash
eosce embed -i input.csv -o output.csv
```

**Comment by GemmaTuron** [comment]
Hi @leoank !

Thanks for this, I've updated the readme accordingly, added some more info on the help command and created a demo file in the lite package
